In [243]:
import pandas as pd
import numpy as np
import scipy

from scipy.stats import spearmanr, chi2_contingency
from statsmodels.stats.weightstats import zconfint

## Task 1

In [244]:
water = pd.read_csv('water.txt', sep='\t')

In [245]:
water.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [246]:
water.shape

(61, 4)

In [247]:
round(water.mortality.corr(water.hardness),4)

-0.6548

## Task 2

In [248]:
round(spearmanr(water.mortality, water.hardness)[0],4)

-0.6317

## Task 3

In [249]:
mortS = water[water.location=='South'].mortality
mortN = water[water.location=='North'].mortality

hardS = water[water.location=='South'].hardness
hardN = water[water.location=='North'].hardness

In [250]:
mortS.shape[0], mortN.shape[0], hardS.shape[0], hardN.shape[0]

(26L, 35L, 26L, 35L)

In [254]:
corrP_S = mortS.corr(hardS)
corrP_N = mortN.corr(hardN)

corrP_S, corrP_N

(-0.60215327154841558, -0.36859783832887177)

In [255]:
-round(min(abs(corrP_S),abs(corrP_N)),4)

-0.3686

## Task 4

In [204]:
a = 203 # женщин хотя бы раз в месяц посещающих бар
b = 239 # мужчин хотя бы раз в месяц посещающих бар
c = 718 # женщин реже, чем раз в месяц посещающих бар
d = 515 # мужчин реже, чем раз в месяц посещающих бар

In [206]:
round((a*d-b*c)/np.sqrt((a+b)*(a+c)*(b+d)*(d+c)),4)

-0.109

## Task 5

In [207]:
mm = np.array([[203, 239], [718, 515]])
mm

array([[203, 239],
       [718, 515]])

In [208]:
chi2_contingency(mm)

(19.407530788543038,
 1.0558987006638725e-05,
 1L,
 array([[ 243.03402985,  198.96597015],
        [ 677.96597015,  555.03402985]]))

## Task 6

In [265]:
N = a+b+c+d

n1 = c+d
n2 = a+b
F = float(c)/n1
M = float(d)/n1

In [266]:
F,M

(0.5823195458231955, 0.41768045417680455)

In [267]:
def confint_int(p1, p2, n1, n2, alpha=0.05):
    z = scipy.stats.norm.ppf(1 - alpha / 2.) 
    left_boundary = (p1 - p2) - z * np.sqrt(p1*(1 - p1)/n1 + p2*(1 - p2)/n2)
    right_boundary = (p1 - p2) + z * np.sqrt(p1*(1 - p1)/n1 + p2*(1 - p2)/n2)
    
    return (left_boundary, right_boundary)

In [268]:
ans = confint_int(M,F,n2,n2)
ans

(-0.22966025180067323, -0.099617931492108569)

In [269]:
round(ans[0],4)

-0.2297

## Task 7

In [218]:
def proportions_diff_z_stat_ind(p1, p2, n1, n2):
    
    P = float(p1*n1 + p2*n2) / (n1 + n2) 
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [219]:
n1 = a+c
n2 = b+d

p1 = float(a)/n1
p2 = float(b)/n2

In [220]:
z_stat = proportions_diff_z_stat_ind(p1, p2, n1, n2)
2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))

8.1534530895766011e-06

## Task 8

In [221]:
A = np.array([[197,111,33],[382,685,331],[110,342,333]])

In [222]:
A

array([[197, 111,  33],
       [382, 685, 331],
       [110, 342, 333]])

In [223]:
A.T

array([[197, 382, 110],
       [111, 685, 342],
       [ 33, 331, 333]])

In [224]:
sum(A.T)

array([ 341, 1398,  785])

In [225]:
sum(A)

array([ 689, 1138,  697])

In [226]:
def chi_sq_calc(matrix):
    
    n = sum(matrix).sum()
    
    n_i = sum(matrix.T)
    n_j = sum(matrix)
    
    ss = 0
    
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ss = ss + (float(matrix[i][j]**2)/(n_i[i]*n_j[j]))
            #print i, j, matrix[i][j]**2, n_i[i], n_j[j], ss
            
    return n*(ss-1)

In [227]:
phi = chi_sq_calc(A)
round(phi,4)

293.6831

In [234]:
from scipy import stats
stats.chi2_contingency(A)[0]

293.68311039689746

## Task 9

In [173]:
dd = int((A.shape[0]-1)*(A.shape[1]-1))
scipy.stats.chi2.sf(phi, dd)

2.4964299580093467e-62

## Task 10

In [158]:
V = np.sqrt(phi/(n*(min(A.shape[0],A.shape[1])-1)))

In [160]:
round(V,4)

0.2412