In [41]:
from sklearn import datasets, metrics
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [42]:
dgts = datasets.load_digits()

test_size = 3./4
k=6

X = dgts.data
y = dgts.target

X_train = X[:X.shape[0]*test_size,:]
X_test = X[X.shape[0]*test_size:,:]
y_train = y[:y.shape[0]*test_size]
y_test = y[y.shape[0]*test_size:]

C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:9: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:10: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [54]:
classifier = NearestNeighbors(n_neighbors=6, algorithm='ball_tree').fit(X_train)
distances, indices = classifier.kneighbors(X_train)

print indices

[[   0  877 1167 1029  464  957]
 [   1   93 1120 1112 1050  466]
 [   2   57   51   50  115  277]
 ..., 
 [1344 1104 1338 1143 1337  518]
 [1345 1215  802  490  146  451]
 [1346  879 1246  835  836  345]]


In [26]:
answer_1 = get_accuracy(X, y, test_size, k)
print("Misclassification rate is "+str(round(answer_1*100,2))+"%")

C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\pavel.dudukin\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:6: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


[[ 1691.  2808.  2875. ...,  1615.  2869.   647.]
 [ 2884.  2153.  2888. ...,  2746.  3532.  2312.]
 [ 2209.  3276.  2719. ...,  1807.  2917.  1429.]
 ..., 
 [ 2538.  1489.  1470. ...,  2778.  1574.  1670.]
 [ 1374.  2359.  2578. ...,  1840.  1916.  1666.]
 [ 2212.  2533.  1932. ...,  2580.  1286.  1488.]]
--------------------------------
[[  203.   332.   408. ...,  4016.  4149.  4152.]
 [  477.   481.   499. ...,  4247.  4276.  4353.]
 [  356.   429.   447. ...,  4462.  4557.  4561.]
 ..., 
 [  434.   471.   526. ...,  3814.  3893.  3913.]
 [  381.   445.   570. ...,  3845.  3870.  4004.]
 [  715.   763.   769. ...,  4089.  4151.  4210.]]
[(83.0, 0), (102.0, 0), (107.0, 0), (107.0, 0), (113.0, 0), (114.0, 0)]
Misclassification rate is 90.44%
