In [2]:
import numpy as np

In [5]:
y = np.array([2,3,4,6])

In [7]:
y

array([2, 3, 4, 6])

In [9]:
print y[1:3]

[3 4]


In [12]:
print y[y>3]

[4 6]


In [14]:
y>3

array([False, False,  True,  True], dtype=bool)

In [15]:
matrix = ([1,2,3],[4,5,6])

In [16]:
matrix

([1, 2, 3], [4, 5, 6])

In [18]:
matrix[1,2]

TypeError: tuple indices must be integers, not tuple

In [19]:
matrix_numpy = np.array(matrix)

In [20]:
a = matrix_numpy[1,2]

In [21]:
print a

6


In [61]:
A = np.random.randn(4,4)

In [60]:
B = np.random.randn(4,4)

In [66]:
print A*B

[[ 0.41165617 -0.29123334 -0.08234462 -0.23662638]
 [-0.44970597  0.11029709 -0.62339657 -0.12156487]
 [ 0.02535307  1.64202582  0.72125936  0.0061557 ]
 [ 0.0108575  -0.00202674  0.74236274 -0.53271917]]


In [69]:
C = np.random.randn(4,1)

In [71]:
print C

[[ 0.95906624]
 [-0.70683562]
 [-1.02104489]
 [ 0.01004737]]


In [73]:
import scipy

In [76]:
from scipy import linalg

In [78]:
from scipy import optimize

In [80]:
D = linalg.solve(A*B, C)

In [82]:
print D

[[ 1.75435438]
 [-0.56661061]
 [-0.18531684]
 [-0.23919435]]


In [83]:
print np.dot(A*B, D)

[[ 0.95906624]
 [-0.70683562]
 [-1.02104489]
 [ 0.01004737]]


In [87]:
def f(x):
    return (x[0]+4)**4+(x[1]+7)**4+6

print f([-4,-7])

6


In [89]:
x_min = optimize.minimize(f,[-10,-3])
print x_min

      fun: 6.00000003180189
 hess_inv: array([[ 156.61285179,  129.70196967],
       [ 129.70196967,  136.6987522 ]])
      jac: array([ -7.21216202e-06,  -3.99351120e-06])
  message: 'Optimization terminated successfully.'
     nfev: 120
      nit: 21
     njev: 30
   status: 0
  success: True
        x: array([-4.012166  , -7.00997351])


In [90]:
x_min.x

array([-4.012166  , -7.00997351])